version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fastapidb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq_app
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  fastapi:
    build:
      context: .
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - db
      - migrate
    volumes:
      - ./documents:/app/documents/
      - ./migrations:/app/migrations/



  celery:
    build:
      context: .
    command: celery -A celery_worker:celery worker
    depends_on:
      - rabbitmq
    volumes:
      - ./documents:/app/documents/



  migrate:
    build:
      context: .
    restart: on-failure
    container_name: alembic_app
    command: alembic upgrade head
    depends_on:
      - db

volumes:
  postgres_data: