"""final

Revision ID: 85c11459c03d
Revises: 8e6783f21bf3
Create Date: 2024-06-07 18:10:21.005693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85c11459c03d'
down_revision = '8e6783f21bf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
